import gzip
configfile: "config/config.yaml"

PANEL_BI = config["panel_bi"]
PANEL_MULTI = config["panel_multi"]
REFERENCE = config["reference"]

ILLUMINA = {}
for line in open(config["sample-info"], 'r'):
	if line.startswith("#"):
		continue
	fields = line.strip().split()
	ILLUMINA[fields[1]] = fields[7]


SAMPLES = [s for s in ILLUMINA.keys()]
OUTNAME = config["outname"]
ALLOWED_VARIANTS = ['snp', 'indels', 'large-deletion', 'large-insertion', 'large-complex']
LEAVE_ONE_OUT_SAMPLES = config["leave_one_out_samples"]
EVALUATION_REGIONS = config["evaluation_regions"]
AVG_ILLUMINA_COV = config["avg_illumina_cov"]

SAMPLING_SIZES = config["sampling_sizes"]
SUBSAMPLING_SIZES = config["subsetting_sizes"]
GENOTYPERS = []#["kage"]

for s in SAMPLING_SIZES:
	GENOTYPERS.append("pangenie-sampled-" + str(s))
for s in SUBSAMPLING_SIZES:
	GENOTYPERS.append("pangenie-subset-" + str(s))


CHROMOSOMES = set(['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY'])
#CHROMOSOMES = set([])
#for line in gzip.open(PANEL_MULTI, 'rt'):
#	if line.startswith('#'):
#		continue
#	fields = line.split('\t')
#	CHROMOSOMES.add(fields[0])
CHROMOSOMES = list(CHROMOSOMES)


include: "rules/leave-one-out_prepare.smk"
include: "rules/leave-one-out_pangenie.smk"
include: "rules/leave-one-out_kage.smk"
include: "rules/evaluation_leave-one-out.smk"
include: "rules/evaluation_panel.smk"


rule all:
	input:
		expand("{results}/leave-one-out/plots/{metric}_{regions}.pdf", results = OUTNAME, metric = ["concordance", "vcfeval-typable", "truvari-typable"], regions = ["biallelic", "multiallelic"] + [k for k in EVALUATION_REGIONS.keys()]),
		expand("{results}/leave-one-out/plots/concordance-vs-untyped_{regions}.pdf", results = OUTNAME, regions = ["biallelic", "multiallelic"] + [k for k in EVALUATION_REGIONS.keys()]),
		expand("{results}/leave-one-out/plots/resources.pdf", results = OUTNAME),
		expand("{results}/leave-one-out/plots/panel-stats.pdf", results = OUTNAME),
		expand("{results}/leave-one-out/plots/recombination-stats.pdf", results = OUTNAME),
		expand("{results}/leave-one-out/plots/afs-missed-alleles.pdf", results = OUTNAME)
