$schema: "https://json-schema.org/draft-07/schema#"
description: Input parameters
properties:
  consensus_haplotypes:
    type: object
    default: {}
  phased_vcfs:
    type: object
    default: {}
  unphased_vcfs:
    type: object
    default: {}
