configfile: "config/config.yaml"

BED = {}
QVS = {}
AGC = config["agc"]
OUTNAME = config["outname"]

# parse sample sheet
for line in open(config["sample_sheet"], 'r'):
	if line.startswith('#'):
		continue
	fields = line.strip().split()
	sample = fields[0]
	BED[sample] = fields[1]
	QVS[sample] = fields[2]
	
SAMPLES = BED.keys()


include: "rules/annotate-histograms.smk"

rule all:
	input:
		expand("{results}/{sample}/plots/{sample}_histogram.pdf", results = OUTNAME, sample = SAMPLES)	
