outname: "results-companion"
sample_sheet: "sample-sheet.tsv"
agc: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/hprc2-companion-paper/evaluation-pipeline/input-files/evaluation-haplotypes.agc"
