# name of the output folder
results: "results-chrY"

# archive with compressed haplotypes
agc:
   CHRY: "/gpfs/project/projects/medbioinf/users/ebler/chrY-paper/prepare-haplotypes/results/consensus.agc"

sample_sheet: "sample-sheet-single.tsv"
cram_ref: "/gpfs/project/projects/medbioinf/data/1000G-ont/1KG_ONT_VIENNA_t2t.fa"

# optional: tab-delimited file: <sample>        <comma sep. names of haploid chroms>
# if not available, set to ""
haploid_chroms: "haploid-chroms-single.txt"

# tab-delimited file of format: <callset>     <sample>_<H1|H2>      name_in_agc
# specifying the name of each haplotype sequence in the AGC archive.
# if not provided, pipeline assumes names follow this pattern: <callset>_<sample>_<H1|H2>
haplotype_names: "names-chrY-single.tsv"
