

consensus_haplotypes:
        HGSVC3-unpolished:
                agc: "../evaluation-pipeline/data/PanGenie-SHAPEIT_all_consensus-haplotypes.agc"
                names: "input-files/pg-unpolished-full.tsv"
        HPRC2-unpolished:
                agc: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/hprc2-companion-paper/genotyping-pipeline/results-hprc2-full/unpolished-haplotypes/pangenie_all-samples_unfiltered_unpolished.agc"
                names: "input-files/readsets-unfiltered-full.tsv"
        HPRC2-polished:
                agc: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/hprc2-companion-paper/genotyping-pipeline/results-hprc2-full/polishing/pangenie_all-samples_unfiltered/all/polished/pangenie_all-samples_unfiltered_25_polished.agc"
                names: "input-files/readsets-25-full.tsv"

phased_vcfs:
        1kGP-HC:
                vcf: "input-files/1kGP_high_coverage_Illumina.filtered.SNV_INDEL_SV_phased_panel.vcf.gz"
                reference: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/data/hg38.no_alt.fa"


outname: "results-hprc2"
reads: "input-files/reads.tsv"

sex_chromosomes:
        - chrX
        - chrY
